global:
  scrape_interval: 15s 


scrape_configs:
  - job_name: "dotnetapp"
    honor_labels: true
    static_configs:
      - targets: ["host.docker.internal:52323"] # Dotnet monitor emitting metrics at this port